# 網站基本設定
title: 半導體與 AI 產業觀察
description: 關注半導體與 AI 產業發展的深度分析
url: https://bear0103papa.github.io
baseurl: /Roger-s-Note

# Jekyll 設定
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 排除檔案
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "../原文草稿" 